//! GENERATED by `tools/gen_tree_rules.py` from libxml2 — do not edit by hand.
//!
//! Every table here is DERIVED: the tool asks the oracle about each cell over the element universe in
//! `gen_tree_rules.ELEMENTS`, partitions the names by measured behaviour, and renders the result.
//! `--check` fails if this file and the oracle have drifted; `--write` regenerates it. To change a rule,
//! change what the oracle is asked, never this file. The hand-written half is in `mod.rs`.

use crate::tokenizer::DataMode;

/// Start-close behaviour classes — the granularity libxml2's `htmlStartClose` pair
/// table actually needs. Two names share a class only if the oracle answers every
/// (open x incoming) cell identically for them in BOTH roles; the partition, the ids
/// and [`start_closes`] below are all derived by `tools/gen_tree_rules.py` from
/// libxml2 itself, over an element universe that is a proven superset of the engine's
/// own names. Do not hand-edit: `--check` fails on drift.
pub mod sc {
    pub const OTHER: u8 = 0; // applet area article aside audio base basefont bdi blink button canvas command data
    // datalist del details dialog embed figcaption figure footer frame header hgroup html
    // image input ins isindex keygen label link main mark marquee math menuitem meta meter nav
    // nobr noembed noframes noscript object output param picture plaintext progress rb rp rt
    // rtc ruby script search section select slot source spacer style summary svg template
    // textarea time track video wbr
    pub const A: u8 = 1; // a
    pub const ABBR_ACRONYM: u8 = 2; // abbr acronym bdo br cite code dfn em iframe img kbd map q samp strong sub sup var
    pub const ADDRESS: u8 = 3; // address
    pub const BIG_S: u8 = 4; // big s small strike tt
    pub const BLOCKQUOTE_BODY: u8 = 5; // blockquote body div frameset hr xmp
    pub const B_I: u8 = 6; // b i
    pub const CAPTION: u8 = 7; // caption
    pub const CENTER: u8 = 8; // center
    pub const COL: u8 = 9; // col
    pub const COLGROUP: u8 = 10; // colgroup
    pub const DD: u8 = 11; // dd
    pub const DIR: u8 = 12; // dir
    pub const DL: u8 = 13; // dl
    pub const DT: u8 = 14; // dt
    pub const FIELDSET: u8 = 15; // fieldset
    pub const FONT: u8 = 16; // font
    pub const FORM: u8 = 17; // form
    pub const H1_H2: u8 = 18; // h1 h2 h3 h4 h5 h6
    pub const HEAD: u8 = 19; // head
    pub const LEGEND: u8 = 20; // legend
    pub const LI: u8 = 21; // li
    pub const LISTING: u8 = 22; // listing
    pub const MENU: u8 = 23; // menu
    pub const OL: u8 = 24; // ol
    pub const OPTGROUP: u8 = 25; // optgroup
    pub const OPTION: u8 = 26; // option
    pub const P: u8 = 27; // p
    pub const PRE: u8 = 28; // pre
    pub const SPAN: u8 = 29; // span
    pub const TABLE: u8 = 30; // table
    pub const TBODY: u8 = 31; // tbody
    pub const TD_TH: u8 = 32; // td th
    pub const TFOOT: u8 = 33; // tfoot
    pub const THEAD: u8 = 34; // thead
    pub const TITLE: u8 = 35; // title
    pub const TR: u8 = 36; // tr
    pub const U: u8 = 37; // u
    pub const UL: u8 = 38; // ul
}

/// Start-close class for a lowercased ASCII tag name.
pub fn sc_id(name: &str) -> u8 {
    match name {
        "a" => sc::A,
        "abbr" | "acronym" | "bdo" | "br" | "cite" | "code" | "dfn" | "em" | "iframe" | "img" |
        "kbd" | "map" | "q" | "samp" | "strong" | "sub" | "sup" | "var" => {
            sc::ABBR_ACRONYM
        }
        "address" => sc::ADDRESS,
        "big" | "s" | "small" | "strike" | "tt" => sc::BIG_S,
        "blockquote" | "body" | "div" | "frameset" | "hr" | "xmp" => sc::BLOCKQUOTE_BODY,
        "b" | "i" => sc::B_I,
        "caption" => sc::CAPTION,
        "center" => sc::CENTER,
        "col" => sc::COL,
        "colgroup" => sc::COLGROUP,
        "dd" => sc::DD,
        "dir" => sc::DIR,
        "dl" => sc::DL,
        "dt" => sc::DT,
        "fieldset" => sc::FIELDSET,
        "font" => sc::FONT,
        "form" => sc::FORM,
        "h1" | "h2" | "h3" | "h4" | "h5" | "h6" => sc::H1_H2,
        "head" => sc::HEAD,
        "legend" => sc::LEGEND,
        "li" => sc::LI,
        "listing" => sc::LISTING,
        "menu" => sc::MENU,
        "ol" => sc::OL,
        "optgroup" => sc::OPTGROUP,
        "option" => sc::OPTION,
        "p" => sc::P,
        "pre" => sc::PRE,
        "span" => sc::SPAN,
        "table" => sc::TABLE,
        "tbody" => sc::TBODY,
        "td" | "th" => sc::TD_TH,
        "tfoot" => sc::TFOOT,
        "thead" => sc::THEAD,
        "title" => sc::TITLE,
        "tr" => sc::TR,
        "u" => sc::U,
        "ul" => sc::UL,
        _ => sc::OTHER,
    }
}

/// True iff an incoming start tag of class `inc` closes an open element of class
/// `top`, per libxml2's `htmlStartClose` pair list. This is a NAME-pair rule, not a
/// content-model one: it closes an open `<b>` for an incoming `<td>` but not an open
/// `<em>`, and an open `<h1>` for an incoming `<table>` but not an open `<div>`.
pub fn start_closes(inc: u8, top: u8) -> bool {
    use sc::*;
    match inc {
        A => matches!(top, A | HEAD),
        ABBR_ACRONYM => matches!(top, HEAD),
        ADDRESS => matches!(top, HEAD | P | UL),
        BIG_S => matches!(top, HEAD),
        BLOCKQUOTE_BODY => matches!(top, HEAD | P),
        B_I => matches!(top, HEAD),
        CAPTION => matches!(top, P),
        CENTER => matches!(top, B_I | FONT | HEAD | P),
        COL => matches!(top, CAPTION | P),
        COLGROUP => matches!(top, CAPTION | COLGROUP | P),
        DD => matches!(top, ADDRESS | DIR | DT | HEAD | LISTING | MENU | P | PRE),
        DIR => matches!(top, HEAD | P),
        DL => matches!(top, ADDRESS | DIR | DT | HEAD | LISTING | MENU | P | PRE),
        DT => matches!(top, ADDRESS | DD | DIR | HEAD | LISTING | MENU | P | PRE),
        FIELDSET => matches!(top, A | H1_H2 | HEAD | LEGEND | LISTING | P | PRE),
        FONT => matches!(top, HEAD),
        FORM => {
            matches!(top, ADDRESS | DIR | DL | FORM | H1_H2 | HEAD | LISTING | MENU | OL | P | PRE | UL)
        }
        H1_H2 => matches!(top, HEAD | P),
        HEAD => matches!(top, P),
        LI => matches!(top, ADDRESS | DL | H1_H2 | HEAD | LI | LISTING | P | PRE),
        LISTING => matches!(top, HEAD | P),
        MENU => matches!(top, HEAD | P | UL),
        OL => matches!(top, HEAD | P),
        OPTGROUP => matches!(top, OPTION),
        OPTION => matches!(top, OPTION),
        P => matches!(top, BIG_S | B_I | H1_H2 | HEAD | P | U),
        PRE => matches!(top, HEAD | P | UL),
        SPAN => matches!(top, HEAD),
        TABLE => matches!(top, A | H1_H2 | HEAD | LISTING | P | PRE),
        TBODY => matches!(top, CAPTION | COLGROUP | P | TBODY | TD_TH | TFOOT | THEAD | TR),
        TD_TH => matches!(top, A | B_I | FONT | P | SPAN | TD_TH | U),
        TFOOT => matches!(top, CAPTION | COLGROUP | P | TBODY | TD_TH | THEAD | TR),
        THEAD => matches!(top, CAPTION | COLGROUP),
        TITLE => matches!(top, P),
        TR => matches!(top, CAPTION | COLGROUP | P | TD_TH | TR),
        U => matches!(top, HEAD),
        UL => matches!(top, ADDRESS | DIR | HEAD | LISTING | MENU | P | PRE),
        _ => false,
    }
}

/// Void elements: no end tag, no children. libxml2 2.14's set, NOT HTML5's — it does
/// NOT treat the HTML5-era `embed`/`source`/`track`/`wbr` as void (it keeps them open
/// as ordinary containers), and it DOES treat the HTML4 `basefont`/`frame`/`isindex`
/// as void. Derived by `tools/gen_tree_rules.py`, same as the classes above.
pub fn is_void(name: &str) -> bool {
    crate::mutate::is_void(
        name,
        matches!(
            name,
            "area" | "base" | "basefont" | "br" | "col" | "frame" | "hr" | "img" | "input" |
            "isindex" | "link" | "meta" | "param"
        ),
    )
}

/// Which part of a SYNTHESIZED document frame a start tag opens, for a document that
/// writes no `<html>`/`<head>`/`<body>` of its own. libxml2 builds the frame anyway and
/// the first element decides which part; see `Matcher::ensure_frame`.
///
/// NOT the same relation as `start_closes(_, sc::HEAD)`: `input`, `noscript`,
/// `template`, `basefont`, `bgsound` and `object` all stay inside a head that is
/// ALREADY open, and none of them opens one. Derived by `tools/gen_tree_rules.py`.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum FrameContent {
    /// opens a `<head>` — the only names that do
    Head,
    /// opens a `<body>` — everything not named in the other two arms
    Body,
    /// Opens neither: `<frameset>`/`<frame>`/`<noframes>` sit directly under `<html>`
    /// and a frameset document has no `<body>` at all. The three frame tags themselves
    /// land here too — they ARE the frame, so they open no part of one.
    Frameset,
}

pub fn frame_content(name: &str) -> FrameContent {
    match name {
        "base" | "link" | "meta" | "script" | "style" | "title" => FrameContent::Head,
        "body" | "frame" | "frameset" | "head" | "html" | "noframes" => FrameContent::Frameset,
        _ => FrameContent::Body,
    }
}

/// How libxml2 tokenizes an element's CONTENT. Anything other than `Normal` means the
/// content is character data: a `<` inside it starts no tag, so a missing name here is
/// not a cosmetic gap — it invents elements that are not in the document
/// (`<iframe><div>x</div></iframe>` matching `div::text`) and desynchronizes every offset
/// after it.
///
/// Derived by `tools/gen_tree_rules.py` over the whole element universe, which is why it
/// is libxml2 2.14's set and not HTML5's: `listing` and `noscript` look like they belong
/// here and do not (libxml2 parses their content as markup, having scripting disabled),
/// while the obsolete `xmp`/`plaintext` do belong. It was a hand-written list of nine
/// names before it was derived.
pub fn data_mode(name: &str) -> DataMode {
    crate::mutate::data_mode(
        name,
        match name {
            "iframe" | "noembed" | "noframes" | "script" | "style" | "xmp" => DataMode::Rawtext,
            "textarea" | "title" => DataMode::Rcdata,
            "plaintext" => DataMode::Plaintext,
            _ => DataMode::Normal,
        },
    )
}

/// Misplaced-END-TAG scope, as libxml2's END PRIORITY per element name: a stray end tag
/// may only unwind elements whose priority is at most its own, so with a HIGHER-priority
/// element still open above the match the end tag is DISCARDED. `<div><table><tr><td>A
/// </div>B` keeps `AB` in the cell (`table` outranks an ordinary name), and
/// `<tr><tbody></tr>` keeps the ROW open (`tbody` outranks `tr`) — the shape a real table
/// generator emits, where treating scope as a flat set nested every later row wrongly.
///
/// Derived and VERIFIED as a single comparison by `tools/gen_tree_rules.py` over every
/// (open x closing) pair in the universe. `</body>`/`</html>` are not here: they close
/// the document unconditionally, which is [`end_tag_discardable`]'s job.
pub fn end_priority(name: &str) -> u8 {
    crate::mutate::end_priority(
        name,
        match name {
            "body" => 6,
            "table" => 5,
            "tbody" | "tfoot" | "thead" => 4,
            "tr" => 3,
            "td" | "th" => 2,
            "div" => 1,
            _ => 0, // every ordinary element: outranks nothing, blocks no end tag
        },
    )
}
