"""
tools/gen_tree_rules.py — derive libxml2's tree-construction rules from the ORACLE, and generate the
engine's start-close table from that derivation.

Why this exists. `implied_close::start_closes` ports libxml2's `htmlStartClose[]` pair list, and the
first port was called "complete" while both its source and its audit universe were hand-picked lists of
names someone remembered. That is the same failure that had already shipped three times here (the
`dd`/`dt` arm, the missing `colgroup` rule, the tag name `s`), and it shipped again: `head`, `listing`,
`xmp` and `plaintext` were absent, so `<html><head><title>T</title><body><p>X</p>` left `<body>` nested
inside `<head>`, and `<div><listing>A<dd>B</dd></div>` put the `<dd>` inside the `<listing>`. A green
gate proved only that the names in the list were right.

So the table is no longer transcribed OR spot-checked. This module:

  1. fixes ONE universe of element names (`ELEMENTS`) and proves it is a superset of both the engine's
     own names and an independent HTML element index (`--check-universe`), so a name cannot be missing
     from the audit because it was missing from the engine;
  2. asks the oracle for the whole (open x incoming) close relation over that universe, plus the void
     set and the per-element data mode, using probes chosen so an UNOBSERVABLE cell is reported as
     unobservable instead of silently guessed;
  3. partitions the names into behaviour classes and RENDERS the Rust table, so the compressed form is
     mechanically derived from the measurement rather than reasoned about;
  4. `--check` fails if `src/implied_close.rs` has drifted from what the oracle says.

`tools/audit_tree_rules.py` consumes the derivation to check the ENGINE (end to end, by value) against
it, and `tools/mutate_rules.py` consumes the class partition to pick mutation representatives. One
derivation, three consumers, no second list to forget a name in.

Usage:
  .venv/bin/python tools/gen_tree_rules.py --check          # gate: Rust table == oracle
  .venv/bin/python tools/gen_tree_rules.py --write          # regenerate the table in place
  .venv/bin/python tools/gen_tree_rules.py --print          # show the rendered Rust
  .venv/bin/python tools/gen_tree_rules.py --report         # human summary of the derivation
"""
from __future__ import annotations

import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

import parsel  # noqa: E402

RUST_SRC = os.path.join(ROOT, "src", "implied_close.rs")
BEGIN = "// ---- BEGIN GENERATED by tools/gen_tree_rules.py — do not edit by hand ----"
END = "// ---- END GENERATED ----"

# ---------------------------------------------------------------------------------------- universe
#
# Every element name a browser-era HTML parser special-cases: HTML 4.01, HTML5 (incl. the current
# element index), and the obsolete/legacy set libxml2 still carries (`listing`, `xmp`, `plaintext`,
# `isindex`, `basefont`, `nobr`, `marquee`, `blink`, `spacer`, `image`, `command`, `keygen`,
# `menuitem`, `rb`/`rtc`, `acronym`, `applet`, `dir`, `frame`/`frameset`/`noframes`, `noembed`).
#
# This list is deliberately NOT derived from the engine. Deriving it from the engine is what made every
# previous audit self-referential: a rule the engine simply does not have has no name to enumerate, so
# a missing rule is invisible. `--check-universe` enforces the containment in the other direction —
# every name the ENGINE mentions must appear HERE, and so must every name an independent index knows.
ELEMENTS = """
a abbr acronym address applet area article aside audio b base basefont bdi bdo big blink blockquote
body br button canvas caption center cite code col colgroup command data datalist dd del details
dfn dialog dir div dl dt em embed fieldset figcaption figure font footer form frame frameset h1 h2
h3 h4 h5 h6 head header hgroup hr html i iframe image img input ins isindex kbd keygen label legend
li link listing main map mark marquee math menu menuitem meta meter nav nobr noembed noframes
noscript object ol optgroup option output p param picture plaintext pre progress q rb rp rt rtc ruby
s samp script search section select slot small source spacer span strike strong style sub summary
sup svg table tbody td template textarea tfoot th thead time title tr track tt u ul var video wbr xmp
""".split()

# The three document-frame start tags. libxml2 accepts each only where it belongs and IGNORES it
# anywhere else (merging attributes onto the element that already exists), so a probe that looks for
# the element cannot tell "was closed" from "was never inserted" — those cells need the text probe
# below, or are reported unobservable.
FRAME_TAGS = ("html", "head", "body")


def _vals(html: str, sels: list[str]) -> list[list[str]]:
    sel = parsel.Selector(text=html)
    return [sel.css(q).getall() for q in sels]


class Oracle:
    """Every tree-construction question this repo asks libxml2, memoized."""

    def __init__(self) -> None:
        self._void: dict[str, bool] | None = None
        self._modes: dict[str, str] | None = None
        self._relation: dict[tuple[str, str], bool | None] | None = None
        self._frame_content: dict[str, str] | None = None

    # ------------------------------------------------------------------ void / ignored / data mode
    def void(self) -> dict[str, bool]:
        """`{name: is_void}`. Void == the element exists but the following text is its PARENT's."""
        if self._void is None:
            self._void = {t: self._probe_void(t) for t in ELEMENTS}
        return self._void

    def _probe_void(self, t: str) -> bool:
        # The wrapper must be an UNKNOWN element, not `<div>`: with `<div>` the probe selector
        # `div::text` also matches the element under test whenever that element IS a div, so `<div>`
        # itself read as void — the wrapper has to be a name that cannot collide with any candidate.
        html = f'<html><body><xwrap><{t} id="Z">A</xwrap></body></html>'
        inside, own = _vals(html, [f"xwrap > {t}::attr(id)", "xwrap::text"])
        # `inside` distinguishes void (element present, no children) from an IGNORED start tag
        # (no element at all) — both leave `A` as the wrapper's own text.
        return bool(inside) and own == ["A"]

    def modes(self) -> dict[str, str]:
        """`{name: "normal"|"rcdata"|"rawtext"|"plaintext"}` — how libxml2 tokenizes the content."""
        if self._modes is None:
            self._modes = {t: self._probe_mode(t) for t in ELEMENTS}
        return self._modes

    def _probe_mode(self, t: str) -> str:
        html = f'<html><body><xwrap><{t}>a&amp;b<zzz>c</zzz></{t}>tail</xwrap></body></html>'
        own, zzz = _vals(html, [f"xwrap > {t}::text", "zzz::text"])
        if zzz:
            return "normal"  # the markup inside became a real element
        if not own:
            return "normal"  # void / ignored / dropped — no text of its own either way
        # its OWN end tag showing up in its text means the mode never ends (PLAINTEXT)
        if f"</{t}>" in own[0]:
            return "plaintext"
        return "rawtext" if "&amp;" in own[0] else "rcdata"

    def frame_content(self) -> dict[str, str]:
        """`{name: "head"|"body"|"frameset"}` — which part of a SYNTHESIZED frame this element starts.

        A document need not write `<html>`/`<head>`/`<body>` at all, and libxml2 builds them anyway: the
        first element decides which. Six names open a `<head>`; `<frameset>`/`<frame>`/`<noframes>` open
        a frameset document that has no body at all; everything else opens a `<body>`.

        This is NOT the same relation as "does this tag close an open `<head>`" (the `head` column of
        `relation()`), and assuming it was is the trap: `input`, `noscript`, `template`, `basefont`,
        `bgsound` and `object` stay inside a head that is already open, yet none of them OPENS one.
        Two questions, two probes, both over the whole universe.
        """
        if self._frame_content is None:
            self._frame_content = {t: self._probe_frame_content(t) for t in ELEMENTS}
        return self._frame_content

    @staticmethod
    def _probe_frame_content(t: str) -> str:
        # A bare document: no frame tags at all, so whatever libxml2 builds around this element is
        # entirely synthesized. `id` rather than text, so a void or raw-text element still answers.
        html = f'<{t} id="Z">A</{t}>'
        in_head, in_body = _vals(html, [f"head > {t}::attr(id)", f"body > {t}::attr(id)"])
        if in_head:
            return "head"
        if in_body:
            return "body"
        return "frameset"  # under <html> directly — a frameset document has no <body>

    def never_open(self) -> set[str]:
        """Names that can never be the OPEN element when a start tag arrives, per the oracle.

        A void element has no content; a raw-text element's content is text, so no start tag is
        tokenized inside it; and `<html>`/`<body>` are only ever closed by end-of-document. Cells with
        such an open element are unobservable by construction, not untested.
        """
        void, modes = self.void(), self.modes()
        return ({t for t in ELEMENTS if void[t]}
                | {t for t in ELEMENTS if modes[t] != "normal"}
                | {"html", "body"})

    # -------------------------------------------------------------------------- the close relation
    def relation(self) -> dict[tuple[str, str], bool | None]:
        """`{(incoming, open): closes}`; `None` where no probe can settle the cell."""
        if self._relation is None:
            never = self.never_open()
            rel: dict[tuple[str, str], bool | None] = {}
            for inc in ELEMENTS:
                for top in ELEMENTS:
                    rel[(inc, top)] = self._probe_close(inc, top, never)
            self._relation = rel
        return self._relation

    def _probe_close(self, inc: str, top: str, never: set[str]) -> bool | None:
        if top in never:
            return None
        if top == "head":
            # `<html>`/`<head>` are ignored here too, so "not inside head" is ambiguous for them.
            if inc in ("html", "head"):
                return None
            return self._probe_close_head(inc)
        if inc in FRAME_TAGS:
            return self._probe_close_text(inc, top)
        return self._probe_close_attr(inc, top)

    @staticmethod
    def _probe_close_attr(inc: str, top: str) -> bool:
        """Is the incoming element a CHILD of the wrapper (closed) or nested inside `top`?

        The wrapper is an unknown element on purpose: libxml2 closes it for nothing, so it stays the
        parent boundary and the probe measures only the pair under test. An ATTRIBUTE, not text, is the
        marker — text inside an open `<table>` is foster-parented, which made `table`-as-open cells read
        as closed whatever the rule.
        """
        html = f'<html><body><xwrap>xx<{top}>aaa<{inc} id="Z">bbb</xwrap></body></html>'
        return bool(_vals(html, [f"xwrap > {inc}::attr(id)"])[0])

    @staticmethod
    def _probe_close_text(inc: str, top: str) -> bool | None:
        """For an IGNORED incoming tag there is no element to locate, so read the open element's text:
        `aaa` alone means it was closed, `aaabbb` means the tag was invisible and the runs joined."""
        html = f'<html><body><xwrap>xx<{top}>aaa<{inc}>bbb</xwrap></body></html>'
        v = _vals(html, [f"xwrap > {top}::text"])[0]
        if v == ["aaa"]:
            return True
        if v == ["aaabbb"]:
            return False
        return None

    @staticmethod
    def _probe_close_head(inc: str) -> bool:
        """The `head` column: does the incoming tag stay in `<head>` or end it? Needs its own probe —
        `<head>` cannot appear inside the body-context wrapper above, which is exactly why the whole
        column was missing from the first port."""
        html = f'<html><head><title>T</title><{inc} id="Z">bbb</head><body>zz</body></html>'
        return not _vals(html, [f"head > {inc}::attr(id)"])[0]


# ----------------------------------------------------------------------------- behaviour classes
def classify(oracle: Oracle) -> tuple[dict[str, str], dict[str, list[str]], dict[str, set[str]]]:
    """Partition `ELEMENTS` into start-close behaviour classes.

    Two names share a class iff they behave identically in BOTH roles: same set of open elements they
    close, and same set of incoming tags that close them. An unobservable cell counts as "does not
    close" — it cannot be reached, so any value is equivalent, and `False` keeps the table small.

    Returns `(name -> class, class -> names, class -> class ids it closes)`.
    """
    rel = oracle.relation()
    sig: dict[str, tuple] = {}
    for t in ELEMENTS:
        row = tuple(bool(rel[(t, x)]) for x in ELEMENTS)      # as the INCOMING tag
        col = tuple(bool(rel[(x, t)]) for x in ELEMENTS)      # as the OPEN element
        sig[t] = (row, col)

    groups: dict[tuple, list[str]] = {}
    for t in ELEMENTS:
        groups.setdefault(sig[t], []).append(t)

    def class_name(names: list[str]) -> str:
        pick = sorted(names)[:2] if len(names) > 1 else sorted(names)
        return "_".join(n.upper() for n in pick)

    empty = (tuple([False] * len(ELEMENTS)),) * 2
    by_class: dict[str, list[str]] = {}
    for s, names in groups.items():
        by_class["OTHER" if s == empty else class_name(names)] = sorted(names)
    if "OTHER" not in by_class:
        by_class["OTHER"] = []  # every unrecognized element lands here

    name_class = {n: c for c, names in by_class.items() for n in names}
    closes: dict[str, set[str]] = {}
    for c, names in by_class.items():
        rep = names[0] if names else None
        closes[c] = ({name_class[x] for x in ELEMENTS if rep and rel[(rep, x)]})
    return name_class, by_class, closes


# ------------------------------------------------------------------------------- Rust rendering
def render_rust(oracle: Oracle) -> str:
    name_class, by_class, closes = classify(oracle)
    void = sorted(t for t in ELEMENTS if oracle.void()[t])
    ordered = ["OTHER"] + sorted(c for c in by_class if c != "OTHER")
    ids = {c: i for i, c in enumerate(ordered)}

    out: list[str] = [BEGIN, ""]
    out.append("/// Start-close behaviour classes — the granularity libxml2's `htmlStartClose` pair")
    out.append("/// table actually needs. Two names share a class only if the oracle answers every")
    out.append("/// (open x incoming) cell identically for them in BOTH roles; the partition, the ids")
    out.append("/// and [`start_closes`] below are all derived by `tools/gen_tree_rules.py` from")
    out.append("/// libxml2 itself, over an element universe that is a proven superset of the engine's")
    out.append("/// own names. Do not hand-edit: `--check` fails on drift.")
    out.append("pub mod sc {")
    for c in ordered:
        members = " ".join(by_class[c]) or "every unrecognized element"
        head, *rest = _wrap_words(members, width=88)
        out.append(f"    pub const {c}: u8 = {ids[c]}; // {head}")
        out += [f"    // {line}" for line in rest]
    out.append("}")
    out.append("")
    out.append("/// Start-close class for a lowercased ASCII tag name.")
    out.append("pub fn sc_id(name: &str) -> u8 {")
    out.append("    match name {")
    for c in ordered:
        if c == "OTHER" or not by_class[c]:
            continue
        pat = " | ".join(f'"{n}"' for n in by_class[c])
        out += _wrap_arm(pat, f"sc::{c},")
    out.append("        _ => sc::OTHER,")
    out.append("    }")
    out.append("}")
    out.append("")
    out.append("/// True iff an incoming start tag of class `inc` closes an open element of class")
    out.append("/// `top`, per libxml2's `htmlStartClose` pair list. This is a NAME-pair rule, not a")
    out.append("/// content-model one: it closes an open `<b>` for an incoming `<td>` but not an open")
    out.append("/// `<em>`, and an open `<h1>` for an incoming `<table>` but not an open `<div>`.")
    out.append("pub fn start_closes(inc: u8, top: u8) -> bool {")
    out.append("    use sc::*;")
    out.append("    match inc {")
    for c in ordered:
        tops = sorted(closes[c], key=lambda t: ids[t])
        if not tops:
            continue
        body = f"matches!(top, {' | '.join(tops)}),"
        out += _wrap_arm(c, body)
    out.append("        _ => false,")
    out.append("    }")
    out.append("}")
    out.append("")
    out.append("/// Void elements: no end tag, no children. libxml2 2.14's set, NOT HTML5's — it does")
    out.append("/// NOT treat the HTML5-era `embed`/`source`/`track`/`wbr` as void (it keeps them open")
    out.append("/// as ordinary containers), and it DOES treat the HTML4 `basefont`/`frame`/`isindex`")
    out.append("/// as void. Derived by `tools/gen_tree_rules.py`, same as the classes above.")
    out.append("pub fn is_void(name: &str) -> bool {")
    out.append("    crate::mutate::is_void(")
    out.append("        name,")
    out.append("        matches!(")
    out.append("            name,")
    pat = " | ".join(f'"{n}"' for n in void)
    for line in _wrap(pat, indent=12, width=96):
        out.append(line)
    out.append("        ),")
    out.append("    )")
    out.append("}")
    out.append("")
    fc = oracle.frame_content()
    out.append("/// Which part of a SYNTHESIZED document frame a start tag opens, for a document that")
    out.append("/// writes no `<html>`/`<head>`/`<body>` of its own. libxml2 builds the frame anyway and")
    out.append("/// the first element decides which part; see `Matcher::ensure_frame`.")
    out.append("///")
    out.append("/// NOT the same relation as `start_closes(_, sc::HEAD)`: `input`, `noscript`,")
    out.append("/// `template`, `basefont`, `bgsound` and `object` all stay inside a head that is")
    out.append("/// ALREADY open, and none of them opens one. Derived by `tools/gen_tree_rules.py`.")
    out.append("#[derive(Clone, Copy, PartialEq, Eq, Debug)]")
    out.append("pub enum FrameContent {")
    out.append("    /// opens a `<head>` — the only names that do")
    out.append("    Head,")
    out.append("    /// opens a `<body>` — everything not named in the other two arms")
    out.append("    Body,")
    out.append("    /// Opens neither: `<frameset>`/`<frame>`/`<noframes>` sit directly under `<html>`")
    out.append("    /// and a frameset document has no `<body>` at all. The three frame tags themselves")
    out.append("    /// land here too — they ARE the frame, so they open no part of one.")
    out.append("    Frameset,")
    out.append("}")
    out.append("")
    out.append("pub fn frame_content(name: &str) -> FrameContent {")
    out.append("    match name {")
    for kind, arm in (("head", "FrameContent::Head"), ("frameset", "FrameContent::Frameset")):
        members = sorted(t for t in ELEMENTS if fc[t] == kind)
        if not members:
            continue
        pat = " | ".join(f'"{n}"' for n in members)
        out += _wrap_arm(pat, f"{arm},")
    out.append("        _ => FrameContent::Body,")
    out.append("    }")
    out.append("}")
    out.append("")
    out.append(END)
    return "\n".join(out) + "\n"


def _wrap_words(text: str, width: int) -> list[str]:
    lines, cur = [], ""
    for w in text.split():
        if cur and len(cur) + 1 + len(w) > width:
            lines.append(cur)
            cur = w
        else:
            cur = f"{cur} {w}".strip()
    lines.append(cur)
    return lines


def _wrap(text: str, indent: int, width: int) -> list[str]:
    """Wrap an already-` | `-joined pattern onto lines that fit rustfmt's width."""
    pad = " " * indent
    lines: list[str] = []
    cur = pad
    for i, piece in enumerate(text.split(" | ")):
        add = piece if cur.strip() == "" else f" | {piece}"
        if len(cur) + len(add) > width and cur.strip():
            lines.append(cur + " |")
            cur = pad + piece
        else:
            cur += add
    lines.append(cur)
    return lines


def _wrap_arm(pattern: str, body: str) -> list[str]:
    """`        <pattern> => <body>` split across lines when it would be too long."""
    one = f"        {pattern} => {body}"
    if len(one) <= 100:
        return [one]
    lines = _wrap(pattern, indent=8, width=96)
    lines[-1] += " => {"
    lines.append(f"            {body.rstrip(',')}")
    lines.append("        }")
    return lines


# ---------------------------------------------------------------------------- universe integrity
def engine_names() -> set[str]:
    """Every element name the ENGINE mentions in a tree-construction rule."""
    names: set[str] = set()
    for rel in ("src/implied_close.rs", "src/tokenizer.rs"):
        src = open(os.path.join(ROOT, rel)).read()
        names |= {m.lower() for m in re.findall(r'"([a-z][a-z0-9]{0,10})"', src)}
        names |= {m.lower() for m in re.findall(r'b"([a-z][a-z0-9]{0,10})"', src)}
    return names


def independent_names() -> set[str]:
    """Element indexes that know nothing about this repo: lxml's own HTML tag definitions (every
    `*_tags` set, which covers HTML4, the deprecated/nonstandard set and HTML5) and the stdlib
    `html.parser`'s CDATA element list. Attribute-name sets in `lxml.html.defs` are excluded — they
    are not elements, and including them made the probe below ask about `aria-*`."""
    import html.parser
    from lxml.html import defs
    out: set[str] = set(html.parser.HTMLParser.CDATA_CONTENT_ELEMENTS)
    for attr in dir(defs):
        if not (attr == "tags" or attr.endswith("_tags")):
            continue
        v = getattr(defs, attr)
        if isinstance(v, (set, frozenset)):
            out |= {x.lower() for x in v}
    return out


def check_universe() -> list[str]:
    """Names that must be in `ELEMENTS` and are not. Empty list == the universe is a proven superset.

    This is the containment that keeps the audit honest, and it runs in the direction that matters: the
    universe is never DERIVED from the engine (a rule the engine lacks has no name to enumerate, which
    is how `colgroup`, `s` and now `head`/`listing` stayed invisible), but every name the engine mentions
    must appear in it, and so must every name an outside index knows.
    """
    have = set(ELEMENTS)
    missing = sorted((engine_names() | independent_names()) - have)
    # The Rust scan is a regex over string literals, so it also picks up attribute names, mutation
    # spec words and doc prose. Only report a candidate that libxml2 actually treats as an element.
    real = []
    for n in missing:
        html = f'<html><body><xwrap><{n}>A</xwrap></body></html>'
        # an unknown name is an ordinary container; anything else (void, ignored, raw text) proves
        # libxml2 special-cases it and it therefore belongs in the universe
        own, inner = _vals(html, ["xwrap::text", f"xwrap > {n}::text"])
        if own == ["A"] or inner != ["A"]:
            real.append(n)
    return real


def current_block() -> str:
    src = open(RUST_SRC).read()
    i, j = src.find(BEGIN), src.find(END)
    if i < 0 or j < 0:
        raise SystemExit(f"{RUST_SRC}: generated-block markers not found")
    return src[i:j + len(END)] + "\n"


def write_block(new: str) -> None:
    src = open(RUST_SRC).read()
    i, j = src.find(BEGIN), src.find(END)
    if i < 0 or j < 0:
        raise SystemExit(f"{RUST_SRC}: generated-block markers not found")
    open(RUST_SRC, "w").write(src[:i] + new.rstrip("\n") + src[j + len(END):])


def report(oracle: Oracle) -> None:
    name_class, by_class, closes = classify(oracle)
    rel = oracle.relation()
    obs = sum(1 for v in rel.values() if v is not None)
    print(f"universe        : {len(ELEMENTS)} element names")
    print(f"close cells     : {len(rel)} ({obs} observable, {len(rel) - obs} unobservable by "
          f"construction)")
    print(f"closes          : {sum(1 for v in rel.values() if v)} pairs")
    print(f"classes         : {len(by_class)}")
    print(f"void            : {' '.join(sorted(t for t in ELEMENTS if oracle.void()[t]))}")
    modes = oracle.modes()
    for m in ("rawtext", "rcdata", "plaintext"):
        print(f"{m:<16}: {' '.join(t for t in ELEMENTS if modes[t] == m)}")
    print("\nclasses:")
    for c in sorted(by_class):
        print(f"  {c:<22} {' '.join(by_class[c])}")
        if closes[c]:
            print(f"  {'':<22}   closes: {' '.join(sorted(closes[c]))}")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit nonzero if the Rust table has drifted")
    ap.add_argument("--write", action="store_true", help="regenerate the table in src/implied_close.rs")
    ap.add_argument("--print", dest="show", action="store_true", help="print the rendered Rust")
    ap.add_argument("--report", action="store_true", help="human summary of the derivation")
    import oracle as oracle_guard
    oracle_guard.add_argument(ap)
    args = ap.parse_args()
    oracle_guard.require(args.allow_old_libxml2)

    o = Oracle()
    if args.report:
        report(o)
        return 0

    missing = check_universe()
    if missing:
        print("UNIVERSE INCOMPLETE — libxml2 special-cases these names and ELEMENTS omits them:")
        print("   " + " ".join(missing))
        return 1

    new = render_rust(o)
    if args.show:
        print(new, end="")
        return 0
    if args.write:
        write_block(new)
        print(f"wrote the generated block into {RUST_SRC} "
              f"({len(new.splitlines())} lines) — run `cargo fmt`/`cargo test`")
        return 0
    if args.check:
        cur = current_block()
        if cur.strip() == new.strip():
            print(f"GATE: src/implied_close.rs matches the oracle over {len(ELEMENTS)} element names "
                  f"-> PASS")
            return 0
        print("GATE: src/implied_close.rs has DRIFTED from the oracle -> FAIL")
        import difflib
        for line in list(difflib.unified_diff(cur.splitlines(), new.splitlines(),
                                              "src/implied_close.rs", "oracle", lineterm=""))[:60]:
            print("  " + line)
        return 1
    ap.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
